config/routes.rb
Rails.application.routes.draw do
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "blogs#index"


 # resources :users

  resource :session, only: [:new, :create, :destroy]

  resources :user_accounts do
    resources :blogs, only: [:new, :create, :index]
  end

  get "signup" => "user_accounts#new"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user_account
end

app/models/user.rb
class User < ApplicationRecord


    validates :name, :password, :email, presence: true


end

app/models/user_account.rb
class UserAccount < ApplicationRecord

  has_many :blogs
  has_secure_password

  validates :name, presence: true
  validates :email, format: { with: /\S+@\S+/},
                    uniqueness: {case_sensitive: false}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    

    private

    def current_user
        UserAccount.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user

    def current_user?(userAcc)
        current_user == userAcc 
    end
    helper_method :current_user?

    def require_signin
        unless current_user
            session[:intended_url] = request.url
            redirect_to new_session_url, alert: "Please sign in first!"
        end
    end
    
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

    before_action :require_signin, except: [:new, :create, :index]
    before_action :require_correct_user, only: [:new, :create]
    

    def index
        
        @blogs = Blog.all
        
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


    def new

    end


    def create
        userAcc = UserAccount.find_by(email: params[:email])
        if userAcc && userAcc.authenticate(params[:password])
            session[:user_id] = userAcc.id
            redirect_to (session[:intended_url] || userAcc), notice: "Welcome back #{userAcc.name}"
            session[:intended_url] = nil
        else
            flash.now[:alert] = "Invalid Email/Password!"
            render :new
        end
    end


    def destroy
        session[:user_id] = nil
       redirect_to user_accounts_url, notice: "You signed out!"
    end

    private

    

end

app/controllers/user_accounts_controller.rb
class UserAccountsController < ApplicationController

    before_action :require_signin, except: [:new, :create]
    before_action :require_correct_user, only: [:edit, :update, :destroy]

    def index
        @userAccs = UserAccount.all
    end

    def show
        @userAcc = UserAccount.find(params[:id])
    end


    def new
        @userAcc = UserAccount.new
    end

    def create
        @userAcc = UserAccount.new(user_account_params)
        if @userAcc.save
            session[:user_id] = @userAcc.id
            redirect_to @userAcc, notice: "Successfully created!"
        else
            render :new
        end
    end


    def edit
    #   @userAcc = UserAccount.find(params[:id])
    end


    def update
    #   @userAcc = UserAccount.find(params[:id])
      if @userAcc = UserAccount.update(user_account_params)
            redirect_to user_account_path, notice: "Successfully updated!"
        else
            render :new
        end
    end


    def destroy
    #   @userAcc = UserAccount.find(params[:id])
      @userAcc.destroy
      session[:user_id] = nil
      redirect_to user_accounts_url, notice: "Account has been deleted!"
    end

    private

    def require_correct_user
        @userAcc = UserAccount.find(params[:id])
        redirect_to user_accounts_url unless current_user?(@userAcc)
    end

    def user_account_params
        params.require(:user_account).
                permit(:name, :email, :password, :password_confirmation)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


    def new
        @user = User.new
    end


    def create
        #  @user = User.new(username: params[:username], email: params[:email], password: params[:password])
           @user = User.new(users_params)
             if @user.save
               # flash.now[:user] = "Successfully added #{@user.username}"  
               flash[:notice] = "Successfully added #{@user.name}"
                 redirect_to new_user_path
             else
                 render :new, status: :unprocessable_entity
                 
             end
         end
     
         def edit
             @user = User.find(params[:id])
         end
         
           def update
             @user = User.find(params[:id])
         
             if @user.update(users_params)
               flash[:notice] = "Successfully Updated #{@user.name}"
               redirect_to @user
             else
               render :edit, status: :unprocessable_entity
             end
           end
         
     
         private
         def users_params
             params.require(:user).permit(:name, :email, :password)
         end


end

app/helpers/application_helper.rb
module ApplicationHelper



end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_accounts_helper.rb
module UserAccountsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/index.html.erb
<div class="container">
  <div class="article_title">
    <h1><%= pluralize(@blogs.size, "Article")%></h1>
  </div>
  
    <% @blogs.each do |blog|%>
        
      <% if session[:user_id] == blog.user_account_id%>
         <div class="article_container">
        <div class="article_title"><span>Author: <%= current_user.name %></span>
        <h1><%= blog.title%></h1> 
            created <%= time_ago_in_words(blog.created_at) %> ago
        </div>
        <div class="article_body">
        <%= blog.body%>
            created <%= time_ago_in_words(blog.created_at) %> ago
        </div>
        </div>
      <%else%>
        <div class="article_container">
            <div class="article_title">
            <h1><%= blog.title%></h1><span><%#= current_user.name %></span>
                created <%= time_ago_in_words(blog.created_at) %> ago
            </div>
            <div class="article_body">
            <%= blog.body%>
                created <%= time_ago_in_words(blog.created_at) %> ago
            </div>
            </div>
      <%end%>
    <% end%>
 </ul>

</div>

app/views/layouts/_header.html.erb
<header>
      <nav class="main_nav">
      <div>
        <div class="logo">
        <%= link_to "logo", root_path, class: "logo-in"%>
        </div>
        <%#= link_to "Show", %>
      </div>
      <ul class="nav_items">
        <% if current_user%>
        <li class="nav_liks">
            <%= link_to current_user.name, current_user%>
        </li>
        <li class="nav_liks">
            <%= link_to "Sign Out", session_path,
                                   data: {
                                      turbo_method: :delete
                                    }%>
                  
        </li>
        <% else%>
        <li class="nav_liks">
          <%= link_to "Sign Up", signup_path, class: "button success"%>
          <%= link_to "Sign In", new_session_path, class: "button success"%>
        </li>
        <% end%>
      </ul>
      </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReFormer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    
      <%= render "layouts/header"%>

      <% flash.each do |type, msg| %>
        <% if notice%>
        <div class="notices">
          <%= msg %>      
        </div>
        <% else%>
         <div class="alerts">
          <%= msg %>      
        </div>
        <% end%>
      <% end %>
     
    <%# end%>
    <%= yield %>
  </body>
</html>

app/views/user_accounts/_form.html.erb
<div class="form">
<%= form_with model: @userAcc do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name%>
    <% @userAcc.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
    <% @userAcc.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :password %><br>
    <%= form.password_field :password %>
    <% @userAcc.errors.full_messages_for(:password).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :password_confirmation %><br>
    <%= form.password_field :password_confirmation %>
    <% @userAcc.errors.full_messages_for(:password_confirmation).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit class: "button success"%>
  </div>
<% end %>
</div>

app/views/user_accounts/edit.html.erb
<div class="container">

    <h1>Sign_up</h1>
    <%= render "form",  @userAccs %>

</div>   

app/views/user_accounts/index.html.erb
<div class="container">
  <div class="article_title">
    <h1><%= pluralize(@userAccs.size, "User")%></h1>
  </div>
  
    <% @userAccs.each do |user|%>
    <div class="article_body">
      <%= link_to user.name, user%>
        created <%= time_ago_in_words(user.created_at) %> ago
    </div>
    <% end%>
 </ul>

</div>

app/views/user_accounts/new.html.erb
<h1>Sign_up</h1>

<%= render "form",  @userAccs %>

app/views/user_accounts/show.html.erb
<div class="container">
  <div class="article_body">
    <h1><%= @userAcc.name%></h1>
    <h2><%= mail_to(@userAcc.email)%></h2>
    <% if current_user?(@userAcc)%>
    <div>
        <%= link_to "Edit Account", edit_user_account_path(@userAcc)%>
        <%= link_to "Delete", user_account_path,
                                   data: {
                                      turbo_method: :delete,
                                      turbo_confirm: "Are you sure?"
                                    }%>
                  
        <%# EDITING ACCC CONTINUE TOMM %>
    </div>
    <% end%>
  </div>
</div>

app/views/users/edit.html.erb
<div class="form">
<%= form_with model: @user do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name%>
    <% @user.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
    <% @user.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :password %><br>
    <%= form.password_field :password %>
    <% @user.errors.full_messages_for(:password).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>   
</div>

app/views/users/new.html.erb
<div class="form">
<%= form_with model: @user do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name%>
    <% @user.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
    <% @user.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :password %><br>
    <%= form.password_field :password %>
    <% @user.errors.full_messages_for(:password).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
</div>